<Label>:
    font_size: 30
    background_color: 0.3, 0.4, 0.5, 1
    color: 1, 1, 1, 1

<Button>:
    font_size: 30
    background_color: 1, 1, 1, 1
    color: 1, 1, 1, 1

<CovMapGrid>:

    GridLayout:
        cols: 1
        size: root.width, root.height
        

        Label:
            id: label1
            text: 'PICK MAP INFO'
        
        Button:
            id: button1
            text: 'CONFIRMED'
            on_press: button1.disabled = True
            on_release: root.request('Confirmed')

        Button:
            id: button2
            text: 'DEATHS'
            on_press: button2.disabled = True
            on_release: root.request('Deaths') 

        Button:
            id: button3
            text: 'RECOVERED'
            on_press: button3.disabled = True 
            on_release: root.request('Recovered')
